In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm, tqdm_notebook

In [3]:
# Data cleaning
def data_formating(file_name,freq=15, filter_outliers=True):
    icu_df = pd.read_csv(file_name)
    
    # data cleaning
    icu_df = icu_df.astype({'outcome_time':'datetime64[ns]','recorded_time':'datetime64[ns]'})
    icu_df = icu_df.replace({'Female':1,'Male':0})
    icu_df1 = icu_df.copy()
    
    adm_t = icu_df1.groupby('dummy_encounter_id')['recorded_time'].aggregate('min')
    proxyend = icu_df1.groupby('dummy_encounter_id')['outcome_time'].aggregate('min')
    first_m = adm_t
    # admission time round down to nearest hour
    adm_t = (adm_t.astype('int') - adm_t.astype('int')%(60*60*10**9)).astype('datetime64[ns]')
    # outcome time round down to nearest hour
    proxyend = (proxyend.astype('int') - proxyend.astype('int')%(60*60*10**9)).astype('datetime64[ns]')
    
    # concate
    #
    icu_df2 = pd.merge(proxyend,icu_df1, left_index=True,right_on='dummy_encounter_id')
    icu_df2 = icu_df2.rename(columns={'outcome_time_x':'proxyend_time','outcome_time_y':'outcome_time'})
    #
    icu_df2 = pd.merge(adm_t,icu_df2, left_index=True,right_on='dummy_encounter_id')
    icu_df2 = icu_df2.rename(columns={'recorded_time_x':'adm_time','recorded_time_y':'recorded_time'})
    #
    icu_df2 = pd.merge(first_m,icu_df2, left_index=True,right_on='dummy_encounter_id')
    icu_df2 = icu_df2.rename(columns={'recorded_time_x':'first_m','recorded_time_y':'recorded_time'})

    # calculate los (original los)
    #icu_df2['los'] = icu_df2['outcome_time']-icu_df2['adm_time']
    icu_df2['los'] = icu_df2['outcome_time']-icu_df2['first_m']
    
    icu_df2 = icu_df2.drop(columns=['first_m'])

    
    # filter out top 1% longest stay
    if filter_outliers:
        los_table = icu_df2.groupby('dummy_encounter_id').first()[['outcome','los']]
        los_table['los'] = los_table['los'].astype('timedelta64[h]')
        ninty_nine_quantile = los_table['los'].quantile(q=0.99,interpolation='lower')
        icu_df2['los'] = icu_df2['los'].astype('timedelta64[h]')
        icu_df2 = icu_df2[icu_df2['los']<=ninty_nine_quantile]
    
    return icu_df2

In [5]:
def slicing(df,start,duration=24,dt_end=12,j_block=15):
    #eligable
    icu_df = df[df['los']>=(duration+dt_end)]
    print('after slicing: ', len(icu_df['dummy_encounter_id'].unique()))
    # first 00hrs
    if start == 'first':
        icu_df['sample_start'] = icu_df['adm_time']
        icu_df = icu_df[(icu_df['recorded_time'] < (icu_df['sample_start'] + pd.Timedelta(hours=duration)))]
        icu_df = icu_df.sort_values(by=['dummy_encounter_id','recorded_time'])
    # last 00hrs
    elif start == 'last':
        icu_df['sample_start'] = icu_df['proxyend_time']- pd.Timedelta(hours=duration+dt_end)
        icu_df = icu_df[(icu_df['recorded_time']>= icu_df['sample_start'])
                         & (icu_df['recorded_time']< (icu_df['sample_start']+ pd.Timedelta(hours=duration)))]
        icu_df = icu_df.sort_values(by=['dummy_encounter_id','recorded_time'])
    # random slice
    elif start == 'random':
        # split into survival and outcome group
        icu_o = icu_df[icu_df['outcome']==1]
        icu_s = icu_df[icu_df['outcome']==0]
        
        # last 00hrs before 00hrs from outcomes for outcome groups
        icu_o['sample_start'] = icu_o['proxyend_time']- pd.Timedelta(hours=duration+dt_end)
        icu_o = icu_o[(icu_o['recorded_time']>= icu_o['sample_start'])
                       &(icu_o['recorded_time']< (icu_o['sample_start']+ pd.Timedelta(hours=duration)))]
        icu_o = icu_o.sort_values(by=['dummy_encounter_id','recorded_time'])
        
        # random slice before 00hrs from outcomes for survival groups
        icu_st = icu_s.groupby('dummy_encounter_id').first()
        icu_st['upper_bound'] = icu_st['proxyend_time'] - pd.Timedelta(hours=(duration+dt_end))
        icu_st['gap_unit'] = (icu_st['upper_bound'] - icu_st['adm_time'] )/pd.Timedelta(minutes=60)
        
        #Randomly draw start time of slices
        sample_start = []
        np.random.seed(0)
        for i,unit in enumerate(icu_st['gap_unit'].to_list()):
            try:
                starttime = icu_st['adm_time'].iloc[i] + np.random.choice(int(unit+1))*pd.Timedelta(minutes=60)
            except:
                print(unit)
                starttime = icu_st['adm_time'].iloc[i]
            sample_start.append(starttime)
        icu_st['sample_start'] = sample_start
        print('before concate; ', len(icu_st.index))
        icu_sm = pd.merge(icu_s,icu_st['sample_start'],right_index=True,left_on='dummy_encounter_id')
        print('after concate; ', len(icu_sm['dummy_encounter_id'].unique()))
        #slice
        icu_sm = icu_sm[(icu_sm['recorded_time']>=icu_sm['sample_start'])
                                &(icu_sm['recorded_time']<icu_sm['sample_start']+pd.Timedelta(hours=duration))]
        icu_sm = icu_sm.sort_values(by=['dummy_encounter_id','recorded_time'])
        print('after slicing; ', len(icu_sm['dummy_encounter_id'].unique()))
        #concat survival and outcome table
        icu_df = pd.concat([icu_o,icu_sm])
        
    return icu_df

In [6]:
#old
# select columns 
def transformer(df,dummies = True, j_block=15,base=True,vitals=True,comments=True,v_set=False,medication=False,notes=False,n_extract=False):
    if base:
        base=[
        'dummy_encounter_id',
            'adm_time',
         'dt_start',
         'outcome',
         'julian_minute_c']
    else: base=[]
        
    if vitals:
        vitals = [
         'hr_entered',
         'rr_entered',
         'bp_entered',
         'temp_entered',
         'spo2_entered']
    else: vitals=[]
        
    if comments:
        comments = [
         'hr_comment',
         'rr_comment',
         'bp_comment',
         'temp_comment',
         'spo2_comment']
    else: comments=[]
        
    if v_set:
        v_set = [
         'one_vital',
         'set_vital']
    else: v_set=[]
        
    if medication:
        medication = [
         'prn',
         'withheld']
    else: medication=[]
        
    if notes:
        notes = [
         'notes']
    else: notes=[]
        
    if n_extract:
        n_extract=[
         'Fall down',
         'Abnormal rate rhythm depth and effort of respirations',
         'Abnormal Mental State',
         'Communication problem',
         'cognitive defects',
         'Impaired blood oxygen',
         'Delusions',
         'General concern',
         'Hallucinations',
         'Chest Pain',
         'Mood disorder',
         'Abnormal Blood Pressure',
         'Abnormal Heart Rhythm',
         'Weight alteration',
         'Improper renal function',
         'abnormal rate rhythm depth and effort of respirations_1',
         'Violence Gesture',
         'Abnormal lab test',
         'Restraint',
         'Aspiration',
         'Suicide Risk',
         'Abnormal Temperature',
         'Monitoring',
         'Incisional pain',
         'cranial nerve palsies',
         'Musculoskeletal Pain',
         'Sign Symptoms of infection',
         'ataxic patterns',
         'hypocalcemia',
         'seizure',
         'pain duration',
         'Diagnosis related with Infection',
         'Improper Airway Clearance',
         'abnormal reflex',
         'Acute onset pain',
         'Abuse',
         'Localized pain',
         'pain killer',
         'Back Pain',
         'Fluid Volume Alteration',
         'Dysuria',
         'Arthralgia',
         'delirium',
         'Cutaneous Pain',
         'Oxygen response',
         'headache',
         'Medication related with Infection']
    else: n_extract=[]

    
    columns = base+vitals+comments+v_set+medication+notes+ n_extract
    
    # Calculate julian time
    df['julian_time'] = df['recorded_time'].dt.time

    a = list(df['julian_time'])
    minute_c = []
    for i in tqdm_notebook(a):
        h,m,s = str(i).split(':')
        #count = (int(h)*4 + int(m)//15+1)
        count = (int(h)*60 + int(m))
        #print((h,m,s), 'count: ', count)
        minute_c.append(count)

    # julian minute_c
    df['julian_minute_c'] = minute_c
    # calculate measurement time to sample start time
    df['dt_start'] = df['recorded_time'] - df['sample_start']

    # select columns
    cleaned = df.loc[:,columns]
    # filter out rows with all 0s in features.
    cleaned = cleaned[cleaned.iloc[:,len(base):].any(axis=1)]
    # create julian time block
    cleaned['jblock'] = pd.cut(cleaned.julian_minute_c,range(0,1441,j_block),right=False)
    if dummies:
        cleaned = pd.get_dummies(cleaned,prefix=['jblock'])
    
    #check number
    outcome = len(cleaned[cleaned['outcome']==1]['dummy_encounter_id'].unique())
    survival = len(cleaned[cleaned['outcome']==0]['dummy_encounter_id'].unique())
    print('with columns: ', columns)
    print('outcome group: ', outcome)
    print('survival group: ', survival)
    return cleaned

In [7]:
# select columns 
def transformer(df,dummies = True, j_block=15,base=True,vitals=True,comments=True,v_set=False,medication=False,notes=False,n_extract=False):
    if base:
        base=[
        'dummy_encounter_id',
            'adm_time',
         'dt_start',
         'outcome',
         'julian_minute_c']
    else: base=[]
        
    if vitals:
        vitals = [
         'hr_entered',
         'rr_entered',
         'bp_entered',
         'temp_entered',
         'spo2_entered']
    else: vitals=[]
        
    if comments:
        comments = [
         'hr_comment',
         'rr_comment',
         'bp_comment',
         'temp_comment',
         'spo2_comment']
    else: comments=[]
        
    if v_set:
        v_set = [
         'one_vital',
         'set_vital']
    else: v_set=[]
        
    if medication:
        medication = [
         'prn',
         'withheld']
    else: medication=[]
        
    if notes:
        notes = [
         'notes']
    else: notes=[]
        
    if n_extract:
        n_extract=[
         'Fall down',
         'Abnormal rate rhythm depth and effort of respirations',
         'Abnormal Mental State',
         'Communication problem',
         'cognitive defects',
         'Impaired blood oxygen',
         'Delusions',
         'General concern',
         'Hallucinations',
         'Chest Pain',
         'Mood disorder',
         'Abnormal Blood Pressure',
         'Abnormal Heart Rhythm',
         'Weight alteration',
         'Improper renal function',
         'abnormal rate rhythm depth and effort of respirations_1',
         'Violence Gesture',
         'Abnormal lab test',
         'Restraint',
         'Aspiration',
         'Suicide Risk',
         'Abnormal Temperature',
         'Monitoring',
         'Incisional pain',
         'cranial nerve palsies',
         'Musculoskeletal Pain',
         'Sign Symptoms of infection',
         'ataxic patterns',
         'hypocalcemia',
         'seizure',
         'pain duration',
         'Diagnosis related with Infection',
         'Improper Airway Clearance',
         'abnormal reflex',
         'Acute onset pain',
         'Abuse',
         'Localized pain',
         'pain killer',
         'Back Pain',
         'Fluid Volume Alteration',
         'Dysuria',
         'Arthralgia',
         'delirium',
         'Cutaneous Pain',
         'Oxygen response',
         'headache',
         'Medication related with Infection']
    else: n_extract=[]

    
    columns = base+vitals+comments+v_set+medication+notes+ n_extract
    
    # Calculate julian time
    df['julian_time'] = df['recorded_time'].dt.time

    a = list(df['julian_time'])
    minute_c = []
    for i in tqdm_notebook(a):
        h,m,s = str(i).split(':')
        #count = (int(h)*4 + int(m)//15+1)
        count = (int(h)*60 + int(m))
        #print((h,m,s), 'count: ', count)
        minute_c.append(count)

    # julian minute_c
    df['julian_minute_c'] = minute_c
    # calculate measurement time to sample start time
    df['dt_start'] = df['recorded_time'] - df['sample_start']

    # select columns
    cleaned = df.loc[:,columns]
    # filter out rows with all 0s in features.
    #cleaned = cleaned[cleaned.iloc[:,len(base):].any(axis=1)]
    
    # create julian time block
    cleaned['jblock'] = pd.cut(cleaned.julian_minute_c,range(0,1441,j_block),right=False)
    if dummies:
        cleaned = pd.get_dummies(cleaned,prefix=['jblock'])
        # input 0s to rows with all 0s in features.
        #cleaned[cleaned.iloc[:,len(base):len(columns)].sum(axis=1) == 0].iloc[:,len(columns):]=0
        #s = cleaned[cleaned.iloc[:,len(base):len(columns)].sum(axis=1) == 0]
        #idx = s.index
        #cleaned.ix[idx,len(columns):] = 0
        
    
    #check number
    outcome = len(cleaned[cleaned['outcome']==1]['dummy_encounter_id'].unique())
    survival = len(cleaned[cleaned['outcome']==0]['dummy_encounter_id'].unique())
    print('with columns: ', columns)
    print('outcome group: ', outcome)
    print('survival group: ', survival)
    return cleaned

In [8]:
def create_dataset(dataset, freq=15):
    periods = int(1440/freq)
    freq = str(freq)+'T'
    # create time floor table, 5min for one step
    Frame = pd.DataFrame(0,columns=dataset.columns, index=pd.timedelta_range(0, periods=periods, freq=freq))
    Frame = Frame.drop(columns=['dummy_encounter_id','adm_time','outcome','julian_minute_c','dt_start'])
    #print(periods)
    
    # split dataset by time
    ticu_stay = dataset[dataset['adm_time']<pd.to_datetime('2016-02-01')]['dummy_encounter_id'].unique()
    hicu_stay = dataset[dataset['adm_time']>=pd.to_datetime('2016-02-01')]['dummy_encounter_id'].unique()
    
    tseqs = []
    tlabels = []
    
    #n = 0
    #loop thru icu stays, training 
    for idx in tqdm_notebook(ticu_stay):
        df_time = dataset[dataset['dummy_encounter_id']==idx]
        label = df_time['outcome'].unique()[0]
        df_time = df_time.drop(columns=['dummy_encounter_id','adm_time','outcome','julian_minute_c'])
        df_time = df_time.set_index('dt_start')
        
        
        #concat with floor table
        df_time = pd.concat([Frame,df_time])
        df_time = df_time.resample(freq).sum()
     
        # collapse count within each time lapse to 1
        df_time.iloc[:,:-1] = df_time.iloc[:,:-1] != 0
        #n+=1
        n_features = len(df_time.columns)
        #print(n_features)
        try:
            assert df_time.to_numpy(dtype='float64').shape == (periods,n_features)
        except:
            print(idx, df_time.to_numpy(dtype='float64').shape)
        tlabels.append(label)
        tseqs.append(df_time.to_numpy(dtype='float64'))
        #
        #if n == 1000:break
    
    hseqs = []
    hlabels = []
    #loop thru icu stays, holdout 
    for idx in tqdm_notebook(hicu_stay):
        df_time = dataset[dataset['dummy_encounter_id']==idx]
        label = df_time['outcome'].unique()[0]
        df_time = df_time.drop(columns=['dummy_encounter_id','adm_time','outcome','julian_minute_c'])
        df_time = df_time.set_index('dt_start')
        
        
        #concat with floor table
        df_time = pd.concat([Frame,df_time])
        df_time = df_time.resample(freq).sum()
     
        # collapse count within each time lapse to 1
        df_time.iloc[:,:-1] = df_time.iloc[:,:-1] != 0
        #n+=1
        n_features = len(df_time.columns)
        #print(n_features)
        try:
            assert df_time.to_numpy(dtype='float64').shape == (periods,n_features)
        except:
            print(idx, df_time.to_numpy(dtype='float64').shape)
        hlabels.append(label)
        hseqs.append(df_time.to_numpy(dtype='float64'))
        
    training_data, training_labels, holdout_data, holdout_labels = np.array(tseqs,dtype='float64'),np.array(tlabels,dtype='float64'), np.array(hseqs,dtype='float64'),np.array(hlabels,dtype='float64')
    print("training_data: {}, training_labels: {}, holdout_data: {}, holdout_labels: {}".format(training_data.shape, training_labels.shape, holdout_data.shape, holdout_labels.shape))
    return training_data, training_labels, holdout_data, holdout_labels

In [9]:
# imput julian variables
def create_dataset(dataset, freq=15):
    periods = int(1440/freq)
    freq = str(freq)+'T'
    # create time floor table, 5min for one step
    Frame = pd.DataFrame(0,columns=dataset.columns, index=pd.timedelta_range(0, periods=periods, freq=freq))
    Frame = Frame.drop(columns=['dummy_encounter_id','adm_time','outcome','julian_minute_c','dt_start'])
    #print(periods)
    
    # split dataset by time
    ticu_stay = dataset[dataset['adm_time']<pd.to_datetime('2016-02-01')]['dummy_encounter_id'].unique()
    hicu_stay = dataset[dataset['adm_time']>=pd.to_datetime('2016-02-01')]['dummy_encounter_id'].unique()
    
    tseqs = []
    tlabels = []
    
    #n = 0
    #loop thru icu stays, training 
    for idx in tqdm_notebook(ticu_stay):
        df_time = dataset[dataset['dummy_encounter_id']==idx]
        label = df_time['outcome'].unique()[0]
        df_time = df_time.drop(columns=['dummy_encounter_id','adm_time','outcome','julian_minute_c'])
        df_time = df_time.set_index('dt_start')
        
        
        #concat with floor table
        df_time = pd.concat([Frame,df_time])
        df_time = df_time.resample(freq).sum()
     
        # collapse count within each time lapse to 1
        df_time.iloc[:,:-1] = df_time.iloc[:,:-1] != 0
        #n+=1
        n_features = len(df_time.columns)
        #print(n_features)
        try:
            assert df_time.to_numpy(dtype='float64').shape == (periods,n_features)
        except:
            print(idx, df_time.to_numpy(dtype='float64').shape)
        tlabels.append(label)
        
        seq = df_time.to_numpy(dtype='float64')
        # imput julian timesteps
        #find first row with jb
        ss = df_time.iloc[:,-periods:]
        st = ss[ss.any(axis=1)].index[0]
        i = ss.index.get_loc(st)
        #find first col with jb
        z = ss.iloc[i,:]!=0
        js = z[z==True].index[0]
        j = ss.columns.get_loc(js)
        #print(i,j)
        col = (j-i)
        rows = [n for n in range(periods)]
        cols = [(col+n)%periods for n in range(periods)]
        p = np.zeros((periods,periods))
        p[rows,cols]=1
        seq[:,-periods:] = p
        # imput julian timesteps
        tseqs.append(seq)
        #
        #if n == 1000:break
    
    hseqs = []
    hlabels = []
    #loop thru icu stays, holdout 
    for idx in tqdm_notebook(hicu_stay):
        df_time = dataset[dataset['dummy_encounter_id']==idx]
        label = df_time['outcome'].unique()[0]
        df_time = df_time.drop(columns=['dummy_encounter_id','adm_time','outcome','julian_minute_c'])
        df_time = df_time.set_index('dt_start')
        
        
        #concat with floor table
        df_time = pd.concat([Frame,df_time])
        df_time = df_time.resample(freq).sum()
     
        # collapse count within each time lapse to 1
        df_time.iloc[:,:-1] = df_time.iloc[:,:-1] != 0
        #n+=1
        n_features = len(df_time.columns)
        #print(n_features)
        try:
            assert df_time.to_numpy(dtype='float64').shape == (periods,n_features)
        except:
            print(idx, df_time.to_numpy(dtype='float64').shape)
        hlabels.append(label)
        seq = df_time.to_numpy(dtype='float64')
        # imput julian timesteps
        #find first row with jb
        ss = df_time.iloc[:,-periods:]
        st = ss[ss.any(axis=1)].index[0]
        i = ss.index.get_loc(st)
        #find first col with jb
        z = ss.iloc[i,:]!=0
        js = z[z==True].index[0]
        j = ss.columns.get_loc(js)
        #print(i,j)
        col = (j-i)
        rows = [n for n in range(periods)]
        cols = [(col+n)%periods for n in range(periods)]
        p = np.zeros((periods,periods))
        p[rows,cols]=1
        seq[:,-periods:] = p
        # imput julian timesteps
        hseqs.append(seq)
        
    training_data, training_labels, holdout_data, holdout_labels = np.array(tseqs,dtype='float64'),np.array(tlabels,dtype='float64'), np.array(hseqs,dtype='float64'),np.array(hlabels,dtype='float64')
    print("training_data: {}, training_labels: {}, holdout_data: {}, holdout_labels: {}".format(training_data.shape, training_labels.shape, holdout_data.shape, holdout_labels.shape))
    return training_data, training_labels, holdout_data, holdout_labels

In [10]:
# data configuration 

file_name = 'dataset_icu.csv'
# time unit 15 minutes
# length of time blocks
freq=60
# filter top %1 longest admission 
filter_outliers=True
icu_df = data_formating(file_name,freq, filter_outliers)

# sampling parameters
start='last'
duration=24
dt_end=12
j_block=freq

random = slicing(icu_df,start,duration,dt_end,j_block)
print('loaded successfully')

#directory
start='first24'

after slicing:  6629

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

loaded successfully

In [37]:

tdata = random[random['adm_time']<pd.to_datetime('2016-02-01')]
hdata = random[random['adm_time']>=pd.to_datetime('2016-02-01')]
random

,adm_time,proxyend_time,dummy_encounter_id,outcome,outcome_time,recorded_time,gender,age,race_cd,ethnicity_cd,...,Fluid Volume Alteration,Dysuria,Arthralgia,delirium,Cutaneous Pain,Oxygen response,headache,Medication related with Infection,los,sample_start
53251,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 02:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
5,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 03:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
79880,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 03:27:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39939,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 04:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
55539,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 04:15:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
79881,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 05:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39940,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 05:44:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39941,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 05:53:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
55540,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 06:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
13321,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 06:02:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
26631,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 06:11:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
80712,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 06:45:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
55541,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 07:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
6,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 08:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
7,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 08:27:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39942,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 08:29:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
13322,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 09:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39943,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 09:32:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
53252,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 10:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
26632,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 11:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
55542,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 11:07:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39944,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 11:10:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
80713,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 12:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
39945,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 12:54:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
79882,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 13:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
80714,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 13:24:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
13323,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 13:45:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
8,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 13:51:00,1,88,6,0,...,0,0,0,1,0,0,0,0,47.0,2013-10-24 02:00:00
79883,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 13:58:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
55543,2013-10-23 15:00:00,2013-10-25 14:00:00,6669,0,2013-10-25 14:04:00,2013-10-24 14:00:00,1,88,6,0,...,0,0,0,0,0,0,0,0,47.0,2013-10-24 02:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535620,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 10:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1535621,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 11:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1505834,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 11:28:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1498385,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 12:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527203,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 13:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527204,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 14:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527205,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 15:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1535622,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 16:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1505835,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 17:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527206,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 18:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527207,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 19:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1505836,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 20:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1544310,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 20:31:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1552198,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 20:39:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1544311,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 20:46:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1498386,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 21:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527208,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 22:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1552199,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 23:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1544312,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-24 23:21:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527209,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 00:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1544313,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 01:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527210,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 02:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1552200,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 03:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1535623,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 04:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527211,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 05:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1505837,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 05:12:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527212,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 05:39:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1527213,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 05:40:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1498387,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 06:00:00,1,76,6,0,...,0,0,0,0,0,0,0,0,74.0,2015-12-24 07:00:00
1520182,2015-12-22 17:00:00,2015-12-25 19:00:00,99999599,0,2015-12-25 19:55:00,2015-12-25 06:19:00,1,76,6,0,...,0,0,1,0,0,0,1,0,74.0,2015-12-24 07:00:00

In [35]:
ts = tdata[tdata['outcome']==0].sum()
to = tdata[tdata['outcome']==1].sum()
hs = hdata[hdata['outcome']==0].sum()
ho = hdata[hdata['outcome']==1].sum()

In [41]:
len(tdata[tdata['outcome']==0]['dummy_encounter_id'].unique()),len(tdata[tdata['outcome']==1]['dummy_encounter_id'].unique()),len(hdata[hdata['outcome']==0]['dummy_encounter_id'].unique()),len(hdata[hdata['outcome']==1]['dummy_encounter_id'].unique())

(4829, 121, 1634, 37)

In [31]:
table = pd.concat([ts,to,hs,ho],axis=1)

table.rename(columns = {0:'Training set: survival n=',1:'Training set: outcome n=',2:'Holdout set: survival n=',3:'Holdout set: outcome n='}).to_csv('table.csv')

In [94]:
#Unit 15mins

In [267]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=15
j_block=15

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=False
v_set=False
medication=False
notes=False
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df3,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_15Tr5.npy',training_data)
np.save(start+'/tlabels_15Tr5.npy',training_labels)
np.save(start+'/hseq_15Tr5.npy',holdout_data)
np.save(start+'/hlabels_15Tr5.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 96, 101), training_labels: (4956,), holdout_data: (1673, 96, 101), holdout_labels: (1673,)

In [268]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=15
j_block=15

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=False
v_set=True
medication=True
notes=False
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u15,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies,j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_15Tr10jd.npy',training_data)
np.save(start+'/tlabels_15Tr10jd.npy',training_labels)
np.save(start+'/hseq_15Tr10jd.npy',holdout_data)
np.save(start+'/hlabels_15Tr10jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'one_vital', 'set_vital', 'prn', 'withheld']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 96, 105), training_labels: (4956,), holdout_data: (1673, 96, 105), holdout_labels: (1673,)

In [269]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=15
j_block=15

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=True
v_set=True
medication=True
notes=True
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u30,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_15Tr15jd.npy',training_data)
np.save(start+'/tlabels_15Tr15jd.npy',training_labels)
np.save(start+'/hseq_15Tr15jd.npy',holdout_data)
np.save(start+'/hlabels_15Tr15jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'hr_comment', 'rr_comment', 'bp_comment', 'temp_comment', 'spo2_comment', 'one_vital', 'set_vital', 'prn', 'withheld', 'notes']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 96, 111), training_labels: (4956,), holdout_data: (1673, 96, 111), holdout_labels: (1673,)

In [270]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=15
j_block=15

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=True
v_set=True
medication=True
notes=True
n_extract=True

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u60,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_15Tr_all.npy',training_data)
np.save(start+'/tlabels_15Tr_all.npy',training_labels)
np.save(start+'/hseq_15Tr_all.npy',holdout_data)
np.save(start+'/hlabels_15Tr_all.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'hr_comment', 'rr_comment', 'bp_comment', 'temp_comment', 'spo2_comment', 'one_vital', 'set_vital', 'prn', 'withheld', 'notes', 'Fall down', 'Abnormal rate rhythm depth and effort of respirations', 'Abnormal Mental State', 'Communication problem', 'cognitive defects', 'Impaired blood oxygen', 'Delusions', 'General concern', 'Hallucinations', 'Chest Pain', 'Mood disorder', 'Abnormal Blood Pressure', 'Abnormal Heart Rhythm', 'Weight alteration', 'Improper renal function', 'abnormal rate rhythm depth and effort of respirations_1', 'Violence Gesture', 'Abnormal lab test', 'Restraint', 'Aspiration', 'Suicide Risk', 'Abnormal Temperature', 'Monitoring', 'Incisional pain', 'cranial nerve palsies', 'Musculoskeletal Pain', 'Sign Symptoms of infection', 'ataxic patterns', 'hypocalcemia', 'seizure', 'pain duration', 'Diagnosis related with Infection', 'Improper Airway Clearance', 'abnormal reflex', 'Acute onset pain', 'Abuse', 'Localized pain', 'pain killer', 'Back Pain', 'Fluid Volume Alteration', 'Dysuria', 'Arthralgia', 'delirium', 'Cutaneous Pain', 'Oxygen response', 'headache', 'Medication related with Infection']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 96, 158), training_labels: (4956,), holdout_data: (1673, 96, 158), holdout_labels: (1673,)

In [271]:
# Unit 30mins

In [272]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=30
j_block=30

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=False
v_set=False
medication=False
notes=False
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#random = slicing(icu_df3,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_30Tr5.npy',training_data)
np.save(start+'/tlabels_30Tr5.npy',training_labels)
np.save(start+'/hseq_30Tr5.npy',holdout_data)
np.save(start+'/hlabels_30Tr5.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 48, 53), training_labels: (4956,), holdout_data: (1673, 48, 53), holdout_labels: (1673,)

In [273]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=30
j_block=30

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=False
v_set=True
medication=True
notes=False
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u30,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_30Tr10jd.npy',training_data)
np.save(start+'/tlabels_30Tr10jd.npy',training_labels)
np.save(start+'/hseq_30Tr10jd.npy',holdout_data)
np.save(start+'/hlabels_30Tr10jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'one_vital', 'set_vital', 'prn', 'withheld']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 48, 57), training_labels: (4956,), holdout_data: (1673, 48, 57), holdout_labels: (1673,)

In [274]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=30
j_block=30

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=True
v_set=True
medication=True
notes=True
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u30,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_30Tr15jd.npy',training_data)
np.save(start+'/tlabels_30Tr15jd.npy',training_labels)
np.save(start+'/hseq_30Tr15jd.npy',holdout_data)
np.save(start+'/hlabels_30Tr15jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'hr_comment', 'rr_comment', 'bp_comment', 'temp_comment', 'spo2_comment', 'one_vital', 'set_vital', 'prn', 'withheld', 'notes']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 48, 63), training_labels: (4956,), holdout_data: (1673, 48, 63), holdout_labels: (1673,)

In [275]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=30
j_block=30

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=True
v_set=True
medication=True
notes=True
n_extract=True

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u30,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_30Tr_all.npy',training_data)
np.save(start+'/tlabels_30Tr_all.npy',training_labels)
np.save(start+'/hseq_30Tr_all.npy',holdout_data)
np.save(start+'/hlabels_30Tr_all.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'hr_comment', 'rr_comment', 'bp_comment', 'temp_comment', 'spo2_comment', 'one_vital', 'set_vital', 'prn', 'withheld', 'notes', 'Fall down', 'Abnormal rate rhythm depth and effort of respirations', 'Abnormal Mental State', 'Communication problem', 'cognitive defects', 'Impaired blood oxygen', 'Delusions', 'General concern', 'Hallucinations', 'Chest Pain', 'Mood disorder', 'Abnormal Blood Pressure', 'Abnormal Heart Rhythm', 'Weight alteration', 'Improper renal function', 'abnormal rate rhythm depth and effort of respirations_1', 'Violence Gesture', 'Abnormal lab test', 'Restraint', 'Aspiration', 'Suicide Risk', 'Abnormal Temperature', 'Monitoring', 'Incisional pain', 'cranial nerve palsies', 'Musculoskeletal Pain', 'Sign Symptoms of infection', 'ataxic patterns', 'hypocalcemia', 'seizure', 'pain duration', 'Diagnosis related with Infection', 'Improper Airway Clearance', 'abnormal reflex', 'Acute onset pain', 'Abuse', 'Localized pain', 'pain killer', 'Back Pain', 'Fluid Volume Alteration', 'Dysuria', 'Arthralgia', 'delirium', 'Cutaneous Pain', 'Oxygen response', 'headache', 'Medication related with Infection']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 48, 110), training_labels: (4956,), holdout_data: (1673, 48, 110), holdout_labels: (1673,)

In [276]:
#Unit 60mins

In [277]:
file_name = 'dataset_icu.csv'

# length of time blocks
freq=60
j_block=60

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=False
v_set=False
medication=False
notes=False
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df3,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_60Tr5jd.npy',training_data)
np.save(start+'/tlabels_60Tr5jd.npy',training_labels)
np.save(start+'/hseq_60Tr5jd.npy',holdout_data)
np.save(start+'/hlabels_60Tr5jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 24, 29), training_labels: (4956,), holdout_data: (1673, 24, 29), holdout_labels: (1673,)

In [278]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=60
freq=60
# filter top %1 longest admission 

j_block=60

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=False
v_set=True
medication=True
notes=False
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u60,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_60Tr10jd.npy',training_data)
np.save(start+'/tlabels_60Tr10jd.npy',training_labels)
np.save(start+'/hseq_60Tr10jd.npy',holdout_data)
np.save(start+'/hlabels_60Tr10jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'one_vital', 'set_vital', 'prn', 'withheld']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 24, 33), training_labels: (4956,), holdout_data: (1673, 24, 33), holdout_labels: (1673,)

In [279]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=60
j_block=60

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=True
v_set=True
medication=True
notes=True
n_extract=False

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u60,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_60Tr15jd.npy',training_data)
np.save(start+'/tlabels_60Tr15jd.npy',training_labels)
np.save(start+'/hseq_60Tr15jd.npy',holdout_data)
np.save(start+'/hlabels_60Tr15jd.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'hr_comment', 'rr_comment', 'bp_comment', 'temp_comment', 'spo2_comment', 'one_vital', 'set_vital', 'prn', 'withheld', 'notes']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 24, 39), training_labels: (4956,), holdout_data: (1673, 24, 39), holdout_labels: (1673,)

In [280]:
#file_name = 'dataset_icu.csv'

# length of time blocks
freq=60
j_block=60

# julian time dummified
dummies = True

# features selection
base=True
vitals=True
comments=True
v_set=True
medication=True
notes=True
n_extract=True

# Data Pipeline
#icu_df3 = data_formating(file_name,freq, filter_outliers)
#last = slicing(icu_df_u60,start,duration,dt_end,j_block)
cleaned = transformer(random,dummies, j_block,base,vitals,comments,v_set,medication,notes,n_extract)
training_data, training_labels, holdout_data, holdout_labels = create_dataset(cleaned,freq)

np.save(start+'/tseq_60Tr_all.npy',training_data)
np.save(start+'/tlabels_60Tr_all.npy',training_labels)
np.save(start+'/hseq_60Tr_all.npy',holdout_data)
np.save(start+'/hlabels_60Tr_all.npy',holdout_labels)

HBox(children=(IntProgress(value=0, max=359823), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered', 'hr_comment', 'rr_comment', 'bp_comment', 'temp_comment', 'spo2_comment', 'one_vital', 'set_vital', 'prn', 'withheld', 'notes', 'Fall down', 'Abnormal rate rhythm depth and effort of respirations', 'Abnormal Mental State', 'Communication problem', 'cognitive defects', 'Impaired blood oxygen', 'Delusions', 'General concern', 'Hallucinations', 'Chest Pain', 'Mood disorder', 'Abnormal Blood Pressure', 'Abnormal Heart Rhythm', 'Weight alteration', 'Improper renal function', 'abnormal rate rhythm depth and effort of respirations_1', 'Violence Gesture', 'Abnormal lab test', 'Restraint', 'Aspiration', 'Suicide Risk', 'Abnormal Temperature', 'Monitoring', 'Incisional pain', 'cranial nerve palsies', 'Musculoskeletal Pain', 'Sign Symptoms of infection', 'ataxic patterns', 'hypocalcemia', 'seizure', 'pain duration', 'Diagnosis related with Infection', 'Improper Airway Clearance', 'abnormal reflex', 'Acute onset pain', 'Abuse', 'Localized pain', 'pain killer', 'Back Pain', 'Fluid Volume Alteration', 'Dysuria', 'Arthralgia', 'delirium', 'Cutaneous Pain', 'Oxygen response', 'headache', 'Medication related with Infection']
outcome group:  158
survival group:  6471

HBox(children=(IntProgress(value=0, max=4956), HTML(value='')))

HBox(children=(IntProgress(value=0, max=1673), HTML(value='')))

training_data: (4956, 24, 86), training_labels: (4956,), holdout_data: (1673, 24, 86), holdout_labels: (1673,)

In [281]:
cleaned.head(1000).to_csv('check1.csv')

In [ ]:
# rowling

In [174]:
# select columns 
def transformer_val(df,dummies = True, j_block=60,base=True,vitals=True,comments=False,v_set=False,medication=False,notes=False,n_extract=False):
    if base:
        base=[
        'dummy_encounter_id',
            'adm_time',
            'proxyend_time',
            'recorded_time',
         'dt_start',
         'outcome',
         'julian_minute_c']
    else: base=[]
        
    if vitals:
        vitals = [
         'hr_entered',
         'rr_entered',
         'bp_entered',
         'temp_entered',
         'spo2_entered']
    else: vitals=[]
        
    if comments:
        comments = [
         'hr_comment',
         'rr_comment',
         'bp_comment',
         'temp_comment',
         'spo2_comment']
    else: comments=[]
        
    if v_set:
        v_set = [
         'one_vital',
         'set_vital']
    else: v_set=[]
        
    if medication:
        medication = [
         'prn',
         'withheld']
    else: medication=[]
        
    if notes:
        notes = [
         'notes']
    else: notes=[]
        
    if n_extract:
        n_extract=[
         'Fall down',
         'Abnormal rate rhythm depth and effort of respirations',
         'Abnormal Mental State',
         'Communication problem',
         'cognitive defects',
         'Impaired blood oxygen',
         'Delusions',
         'General concern',
         'Hallucinations',
         'Chest Pain',
         'Mood disorder',
         'Abnormal Blood Pressure',
         'Abnormal Heart Rhythm',
         'Weight alteration',
         'Improper renal function',
         'abnormal rate rhythm depth and effort of respirations_1',
         'Violence Gesture',
         'Abnormal lab test',
         'Restraint',
         'Aspiration',
         'Suicide Risk',
         'Abnormal Temperature',
         'Monitoring',
         'Incisional pain',
         'cranial nerve palsies',
         'Musculoskeletal Pain',
         'Sign Symptoms of infection',
         'ataxic patterns',
         'hypocalcemia',
         'seizure',
         'pain duration',
         'Diagnosis related with Infection',
         'Improper Airway Clearance',
         'abnormal reflex',
         'Acute onset pain',
         'Abuse',
         'Localized pain',
         'pain killer',
         'Back Pain',
         'Fluid Volume Alteration',
         'Dysuria',
         'Arthralgia',
         'delirium',
         'Cutaneous Pain',
         'Oxygen response',
         'headache',
         'Medication related with Infection']
    else: n_extract=[]

    
    columns = base+vitals+comments+v_set+medication+notes+ n_extract
    
    # Calculate julian time
    df['julian_time'] = df['recorded_time'].dt.time

    a = list(df['julian_time'])
    minute_c = []
    for i in a:
        h,m,s = str(i).split(':')
        #count = (int(h)*4 + int(m)//15+1)
        count = (int(h)*60 + int(m))
        #print((h,m,s), 'count: ', count)
        minute_c.append(count)

    # julian minute_c
    df['julian_minute_c'] = minute_c
    # calculate measurement time to sample start time
    df['dt_start'] = df['recorded_time'] - df['sample_start']

    # select columns
    cleaned = df.loc[:,columns]
    # filter out rows with all 0s in features.
    #cleaned = cleaned[cleaned.iloc[:,len(base):].any(axis=1)]
    
    # create julian time block
    cleaned['jblock'] = pd.cut(cleaned.julian_minute_c,range(0,1441,j_block),right=False)
    if dummies:
        cleaned = pd.get_dummies(cleaned,prefix=['jblock'])
        # input 0s to rows with all 0s in features.
        #cleaned[cleaned.iloc[:,len(base):len(columns)].sum(axis=1) == 0].iloc[:,len(columns):]=0
        #s = cleaned[cleaned.iloc[:,len(base):len(columns)].sum(axis=1) == 0]
        #idx = s.index
        #cleaned.ix[idx,len(columns):] = 0
        
    
    #check number
    #outcome = len(cleaned[cleaned['outcome']==1]['dummy_encounter_id'].unique())
    #survival = len(cleaned[cleaned['outcome']==0]['dummy_encounter_id'].unique())
    #print('with columns: ', columns)
    #print('outcome group: ', outcome)
    #print('survival group: ', survival)
    return cleaned

In [175]:
# imput julian variables
def create_dataset_val(dataset, freq=60):
    periods = int(1440/freq)
    freq = str(freq)+'T'
    # create time floor table, 5min for one step
    Frame = pd.DataFrame(0,columns=dataset.columns, index=pd.timedelta_range(0, periods=periods, freq=freq))
    Frame = Frame.drop(columns=['dummy_encounter_id','adm_time','proxyend_time','outcome','recorded_time','julian_minute_c','dt_start'])
    #print(periods)
    
    
    #n = 0
    #loop thru icu stays, training 
    #df_time = dataset[dataset['dummy_encounter_id']==idx]
    #label = df_time['outcome'].unique()[0]
    df_time = dataset.drop(columns=['dummy_encounter_id','adm_time','proxyend_time','outcome','recorded_time','julian_minute_c'])
    df_time = df_time.set_index('dt_start')
    #print(df_time)

    #concat with floor table
    df_time = pd.concat([Frame,df_time])
    df_time = df_time.resample(freq).sum()

    # collapse count within each time lapse to 1
    df_time.iloc[:,:-1] = df_time.iloc[:,:-1] != 0
    #n+=1
    n_features = len(df_time.columns)
    #print(n_features)
    try:
        assert df_time.to_numpy(dtype='float64').shape == (periods,n_features)
    except:
        print(idx, df_time.to_numpy(dtype='float64').shape)
    #tlabels.append(label)
    #print(df_time)
    seq = df_time.to_numpy(dtype='float64')
    # imput julian timesteps
    #find first row with jb
    ss = df_time.iloc[:,-periods:]
    st = ss[ss.any(axis=1)].index[0]
    i = ss.index.get_loc(st)
    #find first col with jb
    z = ss.iloc[i,:]!=0
    js = z[z==True].index[0]
    j = ss.columns.get_loc(js)
    #print(i,j)
    col = (j-i)
    rows = [n for n in range(periods)]
    cols = [(col+n)%periods for n in range(periods)]
    p = np.zeros((periods,periods))
    p[rows,cols]=1
    seq[:,-periods:] = p
    # imput julian timesteps
    #tseqs.append(seq)
    #
    #if n == 1000:break
    
    #print(seq.shape)
        
    #training_data, training_labels, holdout_data, holdout_labels = np.array(tseqs,dtype='float64'),np.array(tlabels,dtype='float64'), np.array(hseqs,dtype='float64'),np.array(hlabels,dtype='float64')
    #print("training_data: {}, training_labels: {}, holdout_data: {}, holdout_labels: {}".format(training_data.shape, training_labels.shape, holdout_data.shape, holdout_labels.shape))
    return seq

In [196]:
import tensorflow as tf
new_model = tf.keras.models.load_model('GRU')

# Check its architecture
new_model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
gru_11 (GRU)                 (None, 32)                7008
_________________________________________________________________
dropout_11 (Dropout)         (None, 32)                0
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 33
=================================================================
Total params: 7,041
Trainable params: 7,041
Non-trainable params: 0
_________________________________________________________________

In [243]:
#ogroup = icu_df[(icu_df['outcome']==0)&(icu_df['los']>=36)]
#ogroup = ogroup[ogroup['recorded_time']<=ogroup['proxyend_time']]
#adm_idx = ogroup['dummy_encounter_id'].unique()

In [256]:
#random.groupby('dummy_encounter_id').first().describe().to_csv('sample_stats.csv')
#random.sum(axis=0).to_csv('count.csv')
#icu_df[(icu_df['outcome']==1)&(icu_df['los']>=36)].groupby('dummy_encounter_id').first()
#158 admission with outcomes
ogroup = icu_df[(icu_df['outcome']==1)&(icu_df['los']>=36)]
ogroup = ogroup[ogroup['recorded_time']<=ogroup['proxyend_time']]
adm_idx = ogroup['dummy_encounter_id'].unique()
n=0
alert_time = []
# loop through each admission
for idx in tqdm_notebook(adm_idx):
    sample = ogroup[ogroup['dummy_encounter_id']==idx]
    sample['sample_start'] = sample['adm_time']
    sample = sample.sort_values(['recorded_time'])
    cleaned = transformer_val(sample,vitals=True,comments=True,v_set=True,medication=True,notes=True)
    # slide throught each admission
    
    end = cleaned['proxyend_time'].unique()[0]
    adm = cleaned['adm_time'].unique()[0]
    slides = (end-adm)/pd.Timedelta(hours=1)-24
    total = (end-adm)/pd.Timedelta(hours=1)
    print(idx)
    for s in range(int(slides)+1):
        start = adm+pd.Timedelta(hours=1)*s
        #print('slide starts at: ', start)
        slices = cleaned[(cleaned['recorded_time']>= start)
                         & (cleaned['recorded_time']< (start+ pd.Timedelta(hours=24)))]
        slices['dt_start'] = slices['recorded_time'] - start
        if len(slices.index) == 0: pass
        else:
            dataset = create_dataset_val(slices, freq=60)
        #predict
        prob = new_model.predict(dataset[np.newaxis, :])[0][0]
        time_to_endpoint = total-s
        print(time_to_endpoint,prob)
        if prob >=0.5:
            time_to_endpoint = total-s
            alert_time.append([time_to_endpoint,total])
    n+=1
    #break
    if n == 10:        
        break
    #print(slides)

HBox(children=(IntProgress(value=0, max=158), HTML(value='')))

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

154243
56.0 0.4856
55.0 0.44395941
54.0 0.47334623
53.0 0.5769125
52.0 0.7441417
51.0 0.8427067
50.0 0.8751092
49.0 0.878244
48.0 0.8951469
47.0 0.9059375
46.0 0.90624326
45.0 0.89430684
44.0 0.89703715
43.0 0.8628689
42.0 0.7712457
41.0 0.6929573
40.0 0.68444985
39.0 0.635372
38.0 0.5832225
37.0 0.5044094
36.0 0.47633758
35.0 0.45679903
34.0 0.5178707
33.0 0.47214064
32.0 0.47313377
31.0 0.40783733
30.0 0.42972666
29.0 0.55985504
28.0 0.67506474
27.0 0.7995812
26.0 0.85663694
25.0 0.9079432
24.0 0.94333965
542097
48.0 0.76940554
47.0 0.78358006
46.0 0.8212536
45.0 0.8460639
44.0 0.8540122
43.0 0.7879091
42.0 0.63409495
41.0 0.43695155
40.0 0.35188013
39.0 0.2894404
38.0 0.24981822
37.0 0.21230316
36.0 0.2564977
35.0 0.28722653
34.0 0.41686726
33.0 0.39757064
32.0 0.47445664
31.0 0.41400158
30.0 0.44485673
29.0 0.6114384
28.0 0.72274274
27.0 0.784168
26.0 0.78868496
25.0 0.8290695
24.0 0.81701857
2267408
257.0 0.8717528
256.0 0.9129841
255.0 0.9158694
254.0 0.91496265
253.0 0.9258097
252.0 0.9406546
251.0 0.94560033
250.0 0.92206055
249.0 0.90001553
248.0 0.8136975
247.0 0.60846186
246.0 0.405883
245.0 0.28486496
244.0 0.20112166
243.0 0.17943628
242.0 0.17032237
241.0 0.22188468
240.0 0.23075111
239.0 0.3995976
238.0 0.42500484
237.0 0.5022811
236.0 0.4762557
235.0 0.61475885
234.0 0.74235404
233.0 0.8106685
232.0 0.8460277
231.0 0.85359764
230.0 0.8781593
229.0 0.9197579
228.0 0.9055434
227.0 0.91292447
226.0 0.89722174
225.0 0.9004315
224.0 0.85748994
223.0 0.69581693
222.0 0.54448897
221.0 0.39396253
220.0 0.29666647
219.0 0.2525355
218.0 0.24039292
217.0 0.3367761
216.0 0.32319584
215.0 0.5081323
214.0 0.48350745
213.0 0.52475715
212.0 0.4895724
211.0 0.51161575
210.0 0.67963326
209.0 0.7720464
208.0 0.8364515
207.0 0.82039404
206.0 0.790003
205.0 0.8196812
204.0 0.88789564
203.0 0.8975577
202.0 0.8869823
201.0 0.874828
200.0 0.8180557
199.0 0.65537447
198.0 0.52721465
197.0 0.4359648
196.0 0.34289548
195.0 0.31418297
194.0 0.273003
193.0 0.37400377
192.0 0.3901287
191.0 0.4927231
190.0 0.51882553
189.0 0.6070872
188.0 0.6642745
187.0 0.74989074
186.0 0.86387056
185.0 0.8961036
184.0 0.92267585
183.0 0.9183042
182.0 0.93266946
181.0 0.95446056
180.0 0.9640416
179.0 0.95887995
178.0 0.9558882
177.0 0.9607592
176.0 0.92890507
175.0 0.8478791
174.0 0.6960298
173.0 0.5254598
172.0 0.47777516
171.0 0.4713151
170.0 0.42538184
169.0 0.4316334
168.0 0.4205022
167.0 0.47058
166.0 0.4404057
165.0 0.4621679
164.0 0.41446668
163.0 0.4576101
162.0 0.59643346
161.0 0.76721644
160.0 0.8882213
159.0 0.9002198
158.0 0.9044812
157.0 0.94131523
156.0 0.9561814
155.0 0.94674784
154.0 0.94239324
153.0 0.929594
152.0 0.88008285
151.0 0.7582525
150.0 0.6431038
149.0 0.5135569
148.0 0.42692012
147.0 0.39359805
146.0 0.39564934
145.0 0.4568339
144.0 0.51948637
143.0 0.6225323
142.0 0.6373403
141.0 0.6825495
140.0 0.74062854
139.0 0.7939388
138.0 0.8523552
137.0 0.9115908
136.0 0.9415666
135.0 0.95208687
134.0 0.95688534
133.0 0.95053554
132.0 0.9527695
131.0 0.9447738
130.0 0.9518681
129.0 0.94801986
128.0 0.9029029
127.0 0.75366586
126.0 0.5675372
125.0 0.42132315
124.0 0.29950318
123.0 0.2540004
122.0 0.23631315
121.0 0.3721656
120.0 0.42496318
119.0 0.5803837
118.0 0.65920323
117.0 0.73191774
116.0 0.68420297
115.0 0.73858756
114.0 0.8032292
113.0 0.8379524
112.0 0.8586943
111.0 0.82096213
110.0 0.80931246
109.0 0.8272809
108.0 0.8281902
107.0 0.8324529
106.0 0.8241273
105.0 0.8131446
104.0 0.75957316
103.0 0.5261268
102.0 0.36477488
101.0 0.27408713
100.0 0.22483289
99.0 0.21657428
98.0 0.1949798
97.0 0.24598168
96.0 0.24647604
95.0 0.41847068
94.0 0.42536038
93.0 0.48454186
92.0 0.44601542
91.0 0.4888474
90.0 0.60181236
89.0 0.6900171
88.0 0.75445974
87.0 0.74723995
86.0 0.7480301
85.0 0.7917744
84.0 0.81305254
83.0 0.796181
82.0 0.8389132
81.0 0.83343
80.0 0.76281613
79.0 0.5635097
78.0 0.36373925
77.0 0.2659842
76.0 0.2092522
75.0 0.17674607
74.0 0.16891739
73.0 0.21641344
72.0 0.27345318
71.0 0.42234746
70.0 0.4517408
69.0 0.48405817
68.0 0.45359817
67.0 0.4924974
66.0 0.6370923
65.0 0.67778283
64.0 0.7311597
63.0 0.7333107
62.0 0.76702785
61.0 0.8141396
60.0 0.86099714
59.0 0.83278
58.0 0.8240385
57.0 0.82188314
56.0 0.7764354
55.0 0.53357476
54.0 0.36753052
53.0 0.26598054
52.0 0.21352832
51.0 0.18281566
50.0 0.17552596
49.0 0.22389404
48.0 0.22498077
47.0 0.39230072
46.0 0.40161932
45.0 0.40640804
44.0 0.38561314
43.0 0.40792057
42.0 0.5146374
41.0 0.645739
40.0 0.76342577
39.0 0.7767678
38.0 0.8207626
37.0 0.87524515
36.0 0.8965112
35.0 0.9129215
34.0 0.9167277
33.0 0.917354
32.0 0.8594008
31.0 0.6821458
30.0 0.43507418
29.0 0.3448592
28.0 0.2841742
27.0 0.25806233
26.0 0.22863899
25.0 0.27946663
24.0 0.30977795
2462616
40.0 0.5890106
39.0 0.5154743
38.0 0.4739309
37.0 0.39090183
36.0 0.4100443
35.0 0.3660659
34.0 0.52447385
33.0 0.5832276
32.0 0.63037956
31.0 0.60152614
30.0 0.7151649
29.0 0.76682824
28.0 0.86876273
27.0 0.90706676
26.0 0.8917017
25.0 0.9002555
24.0 0.8945626
2608888
300.0 0.96478444
299.0 0.94822395
298.0 0.8851555
297.0 0.81622416
296.0 0.68002963
295.0 0.5583391
294.0 0.48262557
293.0 0.52659917
292.0 0.57256866
291.0 0.6023834
290.0 0.69762236
289.0 0.71674263
288.0 0.7875818
287.0 0.7504215
286.0 0.7727964
285.0 0.7876156
284.0 0.83258015
283.0 0.87281376
282.0 0.87211853
281.0 0.8789024
280.0 0.9058872
279.0 0.9227276
278.0 0.9378747
277.0 0.94295406
276.0 0.9455041
275.0 0.9180345
274.0 0.83352995
273.0 0.72468686
272.0 0.6111701
271.0 0.5360633
270.0 0.48850545
269.0 0.4750741
268.0 0.5183717
267.0 0.5317967
266.0 0.7007161
265.0 0.7714044
264.0 0.8143439
263.0 0.8070596
262.0 0.8354914
261.0 0.8817835
260.0 0.9265739
259.0 0.9496916
258.0 0.9494952
257.0 0.95250773
256.0 0.9661148
255.0 0.96743673
254.0 0.96975404
253.0 0.97377986
252.0 0.96978956
251.0 0.9349075
250.0 0.85978806
249.0 0.7673523
248.0 0.673445
247.0 0.5961917
246.0 0.5396057
245.0 0.5162502
244.0 0.54917747
243.0 0.5343424
242.0 0.7088635
241.0 0.73242855
240.0 0.7721397
239.0 0.7607449
238.0 0.7923516
237.0 0.84321475
236.0 0.8833942
235.0 0.9215679
234.0 0.923312
233.0 0.9299842
232.0 0.9501796
231.0 0.9503477
230.0 0.95283675
229.0 0.95119005
228.0 0.9477801
227.0 0.9220911
226.0 0.8410736
225.0 0.7469885
224.0 0.65462345
223.0 0.5815067
222.0 0.5522823
221.0 0.53775907
220.0 0.6461316
219.0 0.65208423
218.0 0.7837607
217.0 0.79493105
216.0 0.81316274
215.0 0.7892897
214.0 0.8140462
213.0 0.86543244
212.0 0.9029382
211.0 0.93010443
210.0 0.9312986
209.0 0.938451
208.0 0.9482558
207.0 0.96096045
206.0 0.96562386
205.0 0.96501344
204.0 0.96197337
203.0 0.94053656
202.0 0.8737171
201.0 0.78764683
200.0 0.6973409
199.0 0.64834493
198.0 0.57439625
197.0 0.5195309
196.0 0.5685712
195.0 0.5323738
194.0 0.6331899
193.0 0.66440177
192.0 0.72647446
191.0 0.7710639
190.0 0.8206361
189.0 0.8786011
188.0 0.91026324
187.0 0.93774086
186.0 0.93226916
185.0 0.920077
184.0 0.9247803
183.0 0.93326366
182.0 0.926309
181.0 0.9418218
180.0 0.93646145
179.0 0.8983521
178.0 0.78814
177.0 0.67157346
176.0 0.57077056
175.0 0.50307226
174.0 0.4631315
173.0 0.4547509
172.0 0.5029688
171.0 0.48440406
170.0 0.6687723
169.0 0.6918387
168.0 0.7900896
167.0 0.785171
166.0 0.8204107
165.0 0.8727758
164.0 0.9222569
163.0 0.9474834
162.0 0.9479098
161.0 0.9514927
160.0 0.9574936
159.0 0.9590817
158.0 0.96184623
157.0 0.9603758
156.0 0.95871747
155.0 0.93288827
154.0 0.8567485
153.0 0.76188135
152.0 0.66726196
151.0 0.5902167
150.0 0.557945
149.0 0.5411444
148.0 0.5806171
147.0 0.5708159
146.0 0.7374459
145.0 0.75805247
144.0 0.8266525
143.0 0.8135757
142.0 0.8353638
141.0 0.8999013
140.0 0.9257354
139.0 0.9474351
138.0 0.9466866
137.0 0.95851487
136.0 0.9643784
135.0 0.96549827
134.0 0.9608672
133.0 0.95952696
132.0 0.9553258
131.0 0.91552883
130.0 0.79107594
129.0 0.5840877
128.0 0.38965464
127.0 0.3125838
126.0 0.31480932
125.0 0.3391781
124.0 0.41992128
123.0 0.3442822
122.0 0.40923816
121.0 0.49449795
120.0 0.58437145
119.0 0.6262247
118.0 0.6982299
117.0 0.8327189
116.0 0.89098966
115.0 0.94398004
114.0 0.95779216
113.0 0.96812683
112.0 0.9677628
111.0 0.9674113
110.0 0.96855587
109.0 0.95847714
108.0 0.94757015
107.0 0.9140608
106.0 0.8049453
105.0 0.6243023
104.0 0.43470544
103.0 0.32958615
102.0 0.28349432

101.0 0.2655043
100.0 0.28146455
99.0 0.23334827
98.0 0.316652
97.0 0.34983662
96.0 0.43043676
95.0 0.4213167
94.0 0.46716785
93.0 0.56880033
92.0 0.68334544
91.0 0.78923965
90.0 0.8035856
89.0 0.81955445
88.0 0.8696581
87.0 0.86569476
86.0 0.870339
85.0 0.856264
84.0 0.8744359
83.0 0.8170093
82.0 0.6331162
81.0 0.49750465
80.0 0.38670537
79.0 0.29385155
78.0 0.23814456
77.0 0.24919449
76.0 0.28668252
75.0 0.2572849
74.0 0.3770788
73.0 0.37040576
72.0 0.4215043
71.0 0.37810135
70.0 0.40906918
69.0 0.53940654
68.0 0.6537997
67.0 0.7228089
66.0 0.70992035
65.0 0.725599
64.0 0.77859575
63.0 0.7905274
62.0 0.79038686
61.0 0.81595767
60.0 0.8395089
59.0 0.78687054
58.0 0.66359144
57.0 0.5147877
56.0 0.38541287
55.0 0.23846361
54.0 0.23562333
53.0 0.26232085
52.0 0.33446464
51.0 0.36764967
50.0 0.51345193
49.0 0.63097453
48.0 0.68307656
47.0 0.6141563
46.0 0.6345348
45.0 0.70066583
44.0 0.7725563
43.0 0.8371758
42.0 0.84204584
41.0 0.85405964
40.0 0.88119155
39.0 0.890125
38.0 0.9095477
37.0 0.8855456
36.0 0.87664104
35.0 0.7910778
34.0 0.5544698
33.0 0.39783105
32.0 0.293876
31.0 0.22750475
30.0 0.23645964
29.0 0.26049787
28.0 0.3368752
27.0 0.31816941
26.0 0.44310182
25.0 0.52461267
24.0 0.5748969
3995842
202.0 0.9269094
201.0 0.88949597
200.0 0.8898116
199.0 0.91542286
198.0 0.90639365
197.0 0.8911532
196.0 0.88831055
195.0 0.8641854
194.0 0.7871093
193.0 0.60241705
192.0 0.47373375
191.0 0.3470696
190.0 0.28807026
189.0 0.267075
188.0 0.23264699
187.0 0.2748916
186.0 0.26963833
185.0 0.43842041
184.0 0.45834118
183.0 0.54464936
182.0 0.5620641
181.0 0.60681826
180.0 0.7295327
179.0 0.8318647
178.0 0.8942774
177.0 0.9197095
176.0 0.9259777
175.0 0.92651546
174.0 0.91495174
173.0 0.91042966
172.0 0.9171224
171.0 0.8972997
170.0 0.8417617
169.0 0.7437778
168.0 0.59892935
167.0 0.45558465
166.0 0.4010847
165.0 0.37718892
164.0 0.3343996
163.0 0.34810525
162.0 0.29223153
161.0 0.40793884
160.0 0.45664784
159.0 0.46904358
158.0 0.4201515
157.0 0.43834683
156.0 0.50826293
155.0 0.59484833
154.0 0.659561
153.0 0.64593244
152.0 0.68846
151.0 0.72999346
150.0 0.7390198
149.0 0.72323847
148.0 0.7316672
147.0 0.79416513
146.0 0.7537238
145.0 0.55837506
144.0 0.38575304
143.0 0.28901196
142.0 0.22822662
141.0 0.19129167
140.0 0.18032056
139.0 0.21557103
138.0 0.20694646
137.0 0.34152734
136.0 0.30776128
135.0 0.32670397
134.0 0.27469623
133.0 0.28982753
132.0 0.419954
131.0 0.5279914
130.0 0.60470253
129.0 0.6816111
128.0 0.73352104
127.0 0.79858017
126.0 0.8497131
125.0 0.83900005
124.0 0.8396813
123.0 0.84205866
122.0 0.7353044
121.0 0.4983216
120.0 0.32514393
119.0 0.21613887
118.0 0.16268028
117.0 0.17049997
116.0 0.17711744
115.0 0.20253703
114.0 0.26818675
113.0 0.38895983
112.0 0.40715444
111.0 0.47786045
110.0 0.43066615
109.0 0.4628627
108.0 0.5620257
107.0 0.6677251
106.0 0.7563561
105.0 0.740597
104.0 0.7700593
103.0 0.82034594
102.0 0.84996635
101.0 0.8609829
100.0 0.88330907
99.0 0.893508
98.0 0.85124266
97.0 0.70818615
96.0 0.5636455
95.0 0.42682585
94.0 0.35163677
93.0 0.30140847
92.0 0.27946362
91.0 0.30635032
90.0 0.34747553
89.0 0.4412258
88.0 0.43893665
87.0 0.4795017
86.0 0.4920366
85.0 0.53477496
84.0 0.6141864
83.0 0.7028094
82.0 0.78663117
81.0 0.80436033
80.0 0.8172713
79.0 0.8441443
78.0 0.8442423
77.0 0.841527
76.0 0.8411306
75.0 0.8317089
74.0 0.7686441
73.0 0.5498696
72.0 0.38444725
71.0 0.25679946
70.0 0.21811922
69.0 0.19841573
68.0 0.1793657
67.0 0.2021692
66.0 0.18708384
65.0 0.3297472
64.0 0.34666327
63.0 0.39069358
62.0 0.35431772
61.0 0.35579762
60.0 0.43484816
59.0 0.5665599
58.0 0.6563599
57.0 0.63563836
56.0 0.671974
55.0 0.7416874
54.0 0.75974965
53.0 0.7453962
52.0 0.73992324
51.0 0.7291194
50.0 0.6369165
49.0 0.48926106
48.0 0.38937697
47.0 0.2991483
46.0 0.2503961
45.0 0.20865889
44.0 0.18187493
43.0 0.21497737
42.0 0.20611633
41.0 0.29166505
40.0 0.31943718
39.0 0.38868493
38.0 0.36783692
37.0 0.4169886
36.0 0.54895705
35.0 0.6791092
34.0 0.7925214
33.0 0.8230428
32.0 0.86077
31.0 0.8912467
30.0 0.91363406
29.0 0.9155769
28.0 0.9180024
27.0 0.90901846
26.0 0.8286771
25.0 0.6371235
24.0 0.45254257
4331259
72.0 0.6423557
71.0 0.65270936
70.0 0.5306397
69.0 0.44813627
68.0 0.35684377
67.0 0.272883
66.0 0.24142125
65.0 0.2244509
64.0 0.24531537
63.0 0.24979918
62.0 0.34094855
61.0 0.3463754
60.0 0.33382148
59.0 0.28925526
58.0 0.3472806
57.0 0.4892302
56.0 0.60490805
55.0 0.68696
54.0 0.7097031
53.0 0.74325985
52.0 0.76991194
51.0 0.78189725
50.0 0.7907114
49.0 0.8342148
48.0 0.82735556
47.0 0.7756833
46.0 0.5608922
45.0 0.39126065
44.0 0.29119018
43.0 0.2770031
42.0 0.28458086
41.0 0.2423432
40.0 0.25002912
39.0 0.24174725
38.0 0.3255023
37.0 0.3634885
36.0 0.37922037
35.0 0.2915604
34.0 0.21688342
33.0 0.34093285
32.0 0.41974774
31.0 0.5165014
30.0 0.56336015
29.0 0.6086867
28.0 0.65404284
27.0 0.712749
26.0 0.70977855
25.0 0.7288131
24.0 0.7204772
4599448
107.0 0.8657142
106.0 0.7147061
105.0 0.5567567
104.0 0.40382358
103.0 0.3132976
102.0 0.28926393
101.0 0.30231327
100.0 0.35617936
99.0 0.40758958
98.0 0.5452035
97.0 0.6120989
96.0 0.64716256
95.0 0.63338685
94.0 0.66151875
93.0 0.7454826
92.0 0.81041396
91.0 0.8710481
90.0 0.8802195
89.0 0.89775544
88.0 0.9100678
87.0 0.92864466
86.0 0.9156086
85.0 0.9134058
84.0 0.9041653
83.0 0.84666485
82.0 0.6704433
81.0 0.509197
80.0 0.36810896
79.0 0.27974334
78.0 0.25099114
77.0 0.23608287
76.0 0.28407744
75.0 0.3385892
74.0 0.47177944
73.0 0.5112953
72.0 0.56275964
71.0 0.5380743
70.0 0.58539945
69.0 0.6750606
68.0 0.76196957
67.0 0.8363766
66.0 0.84890556
65.0 0.8745383
64.0 0.8989178
63.0 0.90944177
62.0 0.92379385
61.0 0.9245799
60.0 0.91546947
59.0 0.8709215
58.0 0.7287233
57.0 0.5922061
56.0 0.46474406
55.0 0.38760263
54.0 0.34896842
53.0 0.32922566
52.0 0.38109818
51.0 0.41451114
50.0 0.5131451
49.0 0.5888908
48.0 0.59839135
47.0 0.5497041
46.0 0.5893039

KeyboardInterrupt:

In [250]:
alert_time

[[47.0, 47.0],
 [46.0, 47.0],
 [45.0, 47.0],
 [44.0, 47.0],
 [43.0, 47.0],
 [42.0, 47.0],
 [41.0, 47.0],
 [40.0, 47.0],
 [39.0, 47.0],
 [38.0, 47.0],
 [25.0, 47.0],
 [24.0, 47.0],
 [48.0, 49.0],
 [47.0, 49.0],
 [46.0, 49.0],
 [45.0, 49.0],
 [44.0, 49.0],
 [43.0, 49.0],
 [42.0, 49.0],
 [41.0, 49.0],
 [40.0, 49.0],
 [39.0, 49.0],
 [38.0, 49.0],
 [37.0, 49.0],
 [348.0, 350.0],
 [347.0, 350.0],
 [346.0, 350.0],
 [345.0, 350.0],
 [344.0, 350.0],
 [343.0, 350.0],
 [342.0, 350.0],
 [341.0, 350.0],
 [340.0, 350.0],
 [339.0, 350.0],
 [338.0, 350.0],
 [337.0, 350.0],
 [336.0, 350.0],
 [335.0, 350.0],
 [334.0, 350.0],
 [324.0, 350.0],
 [321.0, 350.0],
 [320.0, 350.0],
 [319.0, 350.0],
 [318.0, 350.0],
 [317.0, 350.0],
 [316.0, 350.0],
 [315.0, 350.0],
 [314.0, 350.0],
 [313.0, 350.0],
 [312.0, 350.0],
 [311.0, 350.0],
 [310.0, 350.0],
 [297.0, 350.0],
 [296.0, 350.0],
 [295.0, 350.0],
 [294.0, 350.0],
 [293.0, 350.0],
 [292.0, 350.0],
 [291.0, 350.0],
 [290.0, 350.0],
 [289.0, 350.0],
 [288.0, 350.0],
 [287.0, 350.0],
 [286.0, 350.0],
 [272.0, 350.0],
 [271.0, 350.0],
 [270.0, 350.0],
 [269.0, 350.0],
 [268.0, 350.0],
 [267.0, 350.0],
 [266.0, 350.0],
 [265.0, 350.0],
 [264.0, 350.0],
 [263.0, 350.0],
 [262.0, 350.0],
 [261.0, 350.0],
 [260.0, 350.0],
 [252.0, 350.0],
 [251.0, 350.0],
 [250.0, 350.0],
 [249.0, 350.0],
 [248.0, 350.0],
 [247.0, 350.0],
 [246.0, 350.0],
 [245.0, 350.0],
 [244.0, 350.0],
 [243.0, 350.0],
 [242.0, 350.0],
 [241.0, 350.0],
 [240.0, 350.0],
 [239.0, 350.0],
 [238.0, 350.0],
 [237.0, 350.0],
 [230.0, 350.0],
 [229.0, 350.0],
 [228.0, 350.0],
 [227.0, 350.0],
 [226.0, 350.0],
 [225.0, 350.0],
 [224.0, 350.0],
 [223.0, 350.0],
 [222.0, 350.0],
 [221.0, 350.0],
 [220.0, 350.0],
 [219.0, 350.0],
 [218.0, 350.0],
 [217.0, 350.0],
 [216.0, 350.0],
 [215.0, 350.0],
 [214.0, 350.0],
 [213.0, 350.0],
 [212.0, 350.0],
 [211.0, 350.0],
 [210.0, 350.0],
 [209.0, 350.0],
 [208.0, 350.0],
 [207.0, 350.0],
 [206.0, 350.0],
 [205.0, 350.0],
 [204.0, 350.0],
 [203.0, 350.0],
 [202.0, 350.0],
 [201.0, 350.0],
 [200.0, 350.0],
 [199.0, 350.0],
 [198.0, 350.0],
 [197.0, 350.0],
 [196.0, 350.0],
 [195.0, 350.0],
 [194.0, 350.0],
 [193.0, 350.0],
 [192.0, 350.0],
 [191.0, 350.0],
 [190.0, 350.0],
 [189.0, 350.0],
 [188.0, 350.0],
 [187.0, 350.0],
 [185.0, 350.0],
 [184.0, 350.0],
 [183.0, 350.0],
 [182.0, 350.0],
 [181.0, 350.0],
 [180.0, 350.0],
 [179.0, 350.0],
 [178.0, 350.0],
 [177.0, 350.0],
 [176.0, 350.0],
 [175.0, 350.0],
 [174.0, 350.0],
 [173.0, 350.0],
 [172.0, 350.0],
 [171.0, 350.0],
 [170.0, 350.0],
 [169.0, 350.0],
 [168.0, 350.0],
 [167.0, 350.0],
 [166.0, 350.0],
 [165.0, 350.0],
 [164.0, 350.0],
 [163.0, 350.0],
 [162.0, 350.0],
 [161.0, 350.0],
 [160.0, 350.0],
 [159.0, 350.0],
 [158.0, 350.0],
 [157.0, 350.0],
 [156.0, 350.0],
 [155.0, 350.0],
 [154.0, 350.0],
 [153.0, 350.0],
 [152.0, 350.0],
 [151.0, 350.0],
 [150.0, 350.0],
 [149.0, 350.0],
 [148.0, 350.0],
 [147.0, 350.0],
 [146.0, 350.0],
 [145.0, 350.0],
 [144.0, 350.0],
 [143.0, 350.0],
 [142.0, 350.0],
 [141.0, 350.0],
 [140.0, 350.0],
 [139.0, 350.0],
 [138.0, 350.0],
 [137.0, 350.0],
 [136.0, 350.0],
 [135.0, 350.0],
 [134.0, 350.0],
 [133.0, 350.0],
 [132.0, 350.0],
 [131.0, 350.0],
 [130.0, 350.0],
 [129.0, 350.0],
 [128.0, 350.0],
 [127.0, 350.0],
 [126.0, 350.0],
 [125.0, 350.0],
 [124.0, 350.0],
 [123.0, 350.0],
 [122.0, 350.0],
 [121.0, 350.0],
 [120.0, 350.0],
 [119.0, 350.0],
 [106.0, 350.0],
 [105.0, 350.0],
 [104.0, 350.0],
 [103.0, 350.0],
 [102.0, 350.0],
 [101.0, 350.0],
 [100.0, 350.0],
 [99.0, 350.0],
 [98.0, 350.0],
 [97.0, 350.0],
 [96.0, 350.0],
 [95.0, 350.0],
 [81.0, 350.0],
 [80.0, 350.0],
 [79.0, 350.0],
 [78.0, 350.0],
 [77.0, 350.0],
 [76.0, 350.0],
 [75.0, 350.0],
 [74.0, 350.0],
 [73.0, 350.0],
 [72.0, 350.0],
 [71.0, 350.0],
 [55.0, 350.0],
 [54.0, 350.0],
 [53.0, 350.0],
 [52.0, 350.0],
 [51.0, 350.0],
 [50.0, 350.0],
 [49.0, 350.0],
 [48.0, 350.0],
 [47.0, 350.0],
 [33.0, 350.0],
 [32.0, 350.0],
 [31.0, 350.0],
 [30.0, 350.0],
 [29.0, 350.0],
 [28.0, 350.0],
 [27.0, 350.0],
 [26.0, 350.0],
 [25.0, 350.0],
 [24.0, 350.0],
 [30.0, 40.0],
 [29.0, 40.0],
 [28.0, 40.0],
 [27.0, 40.0],
 [26.0, 40.0],
 [25.0, 40.0],
 [24.0, 40.0],
 [122.0, 122.0],
 [121.0, 122.0],
 [120.0, 122.0],
 [119.0, 122.0],
 [118.0, 122.0],
 [117.0, 122.0],
 [116.0, 122.0],
 [115.0, 122.0],
 [114.0, 122.0],
 [113.0, 122.0],
 [112.0, 122.0],
 [111.0, 122.0],
 [110.0, 122.0],
 [101.0, 122.0],
 [100.0, 122.0],
 [99.0, 122.0],
 [98.0, 122.0],
 [97.0, 122.0],
 [96.0, 122.0],
 [95.0, 122.0],
 [94.0, 122.0],
 [93.0, 122.0],
 [92.0, 122.0],
 [91.0, 122.0],
 [90.0, 122.0],
 [89.0, 122.0],
 [88.0, 122.0],
 [87.0, 122.0],
 [86.0, 122.0],
 [85.0, 122.0],
 [84.0, 122.0],
 [83.0, 122.0],
 [82.0, 122.0],
 [81.0, 122.0],
 [80.0, 122.0],
 [79.0, 122.0],
 [78.0, 122.0],
 [77.0, 122.0],
 [76.0, 122.0],
 [75.0, 122.0],
 [74.0, 122.0],
 [73.0, 122.0],
 [72.0, 122.0],
 [71.0, 122.0],
 [70.0, 122.0],
 [69.0, 122.0],
 [68.0, 122.0],
 [67.0, 122.0],
 [66.0, 122.0],
 [65.0, 122.0],
 [64.0, 122.0],
 [50.0, 122.0],
 [49.0, 122.0],
 [48.0, 122.0],
 [47.0, 122.0],
 [46.0, 122.0],
 [45.0, 122.0],
 [44.0, 122.0],
 [43.0, 122.0],
 [42.0, 122.0],
 [41.0, 122.0],
 [40.0, 122.0],
 [39.0, 122.0],
 [26.0, 122.0],
 [25.0, 122.0],
 [24.0, 122.0],
 [70.0, 70.0],
 [69.0, 70.0],
 [68.0, 70.0],
 [67.0, 70.0],
 [66.0, 70.0],
 [65.0, 70.0],
 [59.0, 70.0],
 [58.0, 70.0],
 [57.0, 70.0],
 [56.0, 70.0],
 [55.0, 70.0],
 [54.0, 70.0],
 [53.0, 70.0],
 [52.0, 70.0],
 [51.0, 70.0],
 [50.0, 70.0],
 [49.0, 70.0],
 [48.0, 70.0],
 [47.0, 70.0],
 [46.0, 70.0],
 [45.0, 70.0],
 [44.0, 70.0],
 [43.0, 70.0],
 [42.0, 70.0],
 [33.0, 70.0],
 [32.0, 70.0],
 [31.0, 70.0],
 [30.0, 70.0],
 [29.0, 70.0],
 [28.0, 70.0],
 [27.0, 70.0],
 [26.0, 70.0],
 [25.0, 70.0],
 [24.0, 70.0],
 [47.0, 47.0],
 [46.0, 47.0],
 [31.0, 47.0],
 [30.0, 47.0],
 [29.0, 47.0],
 [28.0, 47.0],
 [27.0, 47.0],
 [26.0, 47.0],
 [25.0, 47.0],
 [24.0, 47.0],
 [33.0, 41.0],
 [32.0, 41.0],
 [31.0, 41.0],
 [30.0, 41.0],
 [29.0, 41.0],
 [28.0, 41.0],
 [27.0, 41.0],
 [26.0, 41.0],
 [25.0, 41.0],
 [24.0, 41.0],
 [73.0, 80.0],
 [71.0, 80.0],
 [70.0, 80.0],
 [69.0, 80.0],
 [68.0, 80.0],
 [67.0, 80.0],
 [66.0, 80.0],
 [65.0, 80.0],
 [47.0, 80.0],
 [46.0, 80.0],
 [45.0, 80.0],
 [44.0, 80.0],
 [43.0, 80.0],
 [42.0, 80.0],
 [41.0, 80.0],
 [25.0, 80.0],
 [24.0, 80.0],
 [92.0, 92.0],
 [91.0, 92.0],
 [90.0, 92.0],
 [89.0, 92.0],
 [88.0, 92.0],
 [87.0, 92.0],
 [86.0, 92.0],
 [85.0, 92.0],
 [84.0, 92.0],
 [83.0, 92.0],
 [82.0, 92.0],
 [81.0, 92.0],
 [80.0, 92.0],
 [79.0, 92.0],
 [78.0, 92.0],
 [77.0, 92.0],
 [76.0, 92.0],
 [75.0, 92.0],
 [74.0, 92.0],
 [73.0, 92.0],
 [72.0, 92.0],
 [71.0, 92.0],
 [70.0, 92.0],
 [69.0, 92.0],
 [68.0, 92.0],
 [67.0, 92.0],
 [66.0, 92.0],
 [65.0, 92.0],
 [62.0, 92.0],
 [60.0, 92.0],
 [59.0, 92.0],
 [58.0, 92.0],
 [57.0, 92.0],
 [56.0, 92.0],
 [55.0, 92.0],
 [54.0, 92.0],
 [53.0, 92.0],
 [52.0, 92.0],
 [51.0, 92.0],
 [50.0, 92.0],
 [49.0, 92.0],
 [48.0, 92.0],
 [47.0, 92.0],
 [46.0, 92.0],
 [45.0, 92.0],
 [44.0, 92.0],
 [43.0, 92.0],
 [34.0, 92.0],
 [33.0, 92.0],
 [32.0, 92.0],
 [31.0, 92.0],
 [30.0, 92.0],
 [29.0, 92.0],
 [28.0, 92.0],
 [27.0, 92.0],
 [26.0, 92.0],
 [25.0, 92.0],
 [24.0, 92.0]]

In [251]:
slices
new_model.predict(dataset[np.newaxis, :])
#new_model.predict?

array([[0.96113396]], dtype=float32)

In [161]:
sample = ogroup[ogroup['dummy_encounter_id']==542097]
sample['sample_start'] = sample['adm_time']
sample = sample.sort_values(['recorded_time'])
cleaned = transformer_val(sample)
cleaned

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

HBox(children=(IntProgress(value=0, max=104), HTML(value='')))

with columns:  ['dummy_encounter_id', 'adm_time', 'proxyend_time', 'recorded_time', 'dt_start', 'outcome', 'julian_minute_c', 'hr_entered', 'rr_entered', 'bp_entered', 'temp_entered', 'spo2_entered']
outcome group:  1
survival group:  0

,dummy_encounter_id,adm_time,proxyend_time,recorded_time,dt_start,outcome,julian_minute_c,hr_entered,rr_entered,bp_entered,...,"jblock_[840, 900)","jblock_[900, 960)","jblock_[960, 1020)","jblock_[1020, 1080)","jblock_[1080, 1140)","jblock_[1140, 1200)","jblock_[1200, 1260)","jblock_[1260, 1320)","jblock_[1320, 1380)","jblock_[1380, 1440)"
56985,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 17:45:00,0 days 00:45:00,1,1065,1,1,1,...,0,0,0,1,0,0,0,0,0,0
54025,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 17:47:00,0 days 00:47:00,1,1067,0,0,1,...,0,0,0,1,0,0,0,0,0,0
831,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 17:55:00,0 days 00:55:00,1,1075,0,0,0,...,0,0,0,1,0,0,0,0,0,0
27394,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 18:00:00,0 days 01:00:00,1,1080,1,1,1,...,0,0,0,0,1,0,0,0,0,0
56986,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 18:02:00,0 days 01:02:00,1,1082,0,0,0,...,0,0,0,0,1,0,0,0,0,0
40744,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 18:27:00,0 days 01:27:00,1,1107,1,1,0,...,0,0,0,0,1,0,0,0,0,0
80681,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 18:30:00,0 days 01:30:00,1,1110,1,1,0,...,0,0,0,0,1,0,0,0,0,0
54026,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 18:49:00,0 days 01:49:00,1,1129,0,0,0,...,0,0,0,0,1,0,0,0,0,0
40745,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 18:57:00,0 days 01:57:00,1,1137,1,0,0,...,0,0,0,0,1,0,0,0,0,0
832,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 19:00:00,0 days 02:00:00,1,1140,1,1,1,...,0,0,0,0,0,1,0,0,0,0
80682,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 20:00:00,0 days 03:00:00,1,1200,1,1,1,...,0,0,0,0,0,0,1,0,0,0
14189,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 20:13:00,0 days 03:13:00,1,1213,1,1,0,...,0,0,0,0,0,0,1,0,0,0
54027,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 21:00:00,0 days 04:00:00,1,1260,1,1,1,...,0,0,0,0,0,0,0,1,0,0
27395,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 21:38:00,0 days 04:38:00,1,1298,0,0,0,...,0,0,0,0,0,0,0,1,0,0
56987,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 22:00:00,0 days 05:00:00,1,1320,1,1,1,...,0,0,0,0,0,0,0,0,1,0
40746,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-20 23:00:00,0 days 06:00:00,1,1380,1,1,1,...,0,0,0,0,0,0,0,0,0,1
833,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 00:00:00,0 days 07:00:00,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
82139,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 00:25:00,0 days 07:25:00,1,25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14190,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 01:00:00,0 days 08:00:00,1,60,1,1,1,...,0,0,0,0,0,0,0,0,0,0
80683,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 01:10:00,0 days 08:10:00,1,70,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82140,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 02:00:00,0 days 09:00:00,1,120,1,1,1,...,0,0,0,0,0,0,0,0,0,0
56988,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 03:00:00,0 days 10:00:00,1,180,1,1,1,...,0,0,0,0,0,0,0,0,0,0
40747,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 04:00:00,0 days 11:00:00,1,240,1,1,1,...,0,0,0,0,0,0,0,0,0,0
80684,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 05:00:00,0 days 12:00:00,1,300,1,1,1,...,0,0,0,0,0,0,0,0,0,0
54028,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 05:03:00,0 days 12:03:00,1,303,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82141,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 05:11:00,0 days 12:11:00,1,311,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82142,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 06:00:00,0 days 13:00:00,1,360,1,1,1,...,0,0,0,0,0,0,0,0,0,0
834,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 06:44:00,0 days 13:44:00,1,404,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14191,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 07:00:00,0 days 14:00:00,1,420,1,1,1,...,0,0,0,0,0,0,0,0,0,0
14192,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-21 07:37:00,0 days 14:37:00,1,457,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57203,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 01:00:00,1 days 08:00:00,1,60,1,1,1,...,0,0,0,0,0,0,0,0,0,0
57204,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 02:00:00,1 days 09:00:00,1,120,1,1,1,...,0,0,0,0,0,0,0,0,0,0
840,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 03:00:00,1 days 10:00:00,1,180,1,1,1,...,0,0,0,0,0,0,0,0,0,0
14198,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 03:01:00,1 days 10:01:00,1,181,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80693,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 04:00:00,1 days 11:00:00,1,240,1,1,1,...,0,0,0,0,0,0,0,0,0,0
40754,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 05:00:00,1 days 12:00:00,1,300,1,1,1,...,0,0,0,0,0,0,0,0,0,0
27401,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 05:37:00,1 days 12:37:00,1,337,0,0,0,...,0,0,0,0,0,0,0,0,0,0
841,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 06:00:00,1 days 13:00:00,1,360,1,1,1,...,0,0,0,0,0,0,0,0,0,0
27402,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 06:40:00,1 days 13:40:00,1,400,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14199,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 06:44:00,1 days 13:44:00,1,404,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82147,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 07:00:00,1 days 14:00:00,1,420,1,1,1,...,0,0,0,0,0,0,0,0,0,0
82148,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 08:00:00,1 days 15:00:00,1,480,1,1,1,...,0,0,0,0,0,0,0,0,0,0
40755,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 08:25:00,1 days 15:25:00,1,505,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54034,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 08:27:00,1 days 15:27:00,1,507,1,0,0,...,0,0,0,0,0,0,0,0,0,0
54035,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 08:30:00,1 days 15:30:00,1,510,0,0,0,...,0,0,0,0,0,0,0,0,0,0
842,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 09:41:00,1 days 16:41:00,1,581,0,0,0,...,0,0,0,0,0,0,0,0,0,0
843,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 10:00:00,1 days 17:00:00,1,600,1,1,1,...,0,0,0,0,0,0,0,0,0,0
54036,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 11:00:00,1 days 18:00:00,1,660,1,1,1,...,0,0,0,0,0,0,0,0,0,0
27403,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 11:38:00,1 days 18:38:00,1,698,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57205,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 11:44:00,1 days 18:44:00,1,704,0,0,0,...,0,0,0,0,0,0,0,0,0,0
844,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 11:46:00,1 days 18:46:00,1,706,1,1,0,...,0,0,0,0,0,0,0,0,0,0
82149,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 12:00:00,1 days 19:00:00,1,720,1,1,1,...,0,0,0,0,0,0,0,0,0,0
80694,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 13:00:00,1 days 20:00:00,1,780,1,1,1,...,0,0,0,0,0,0,0,0,0,0
57206,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 14:00:00,1 days 21:00:00,1,840,1,1,1,...,1,0,0,0,0,0,0,0,0,0
40756,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 14:07:00,1 days 21:07:00,1,847,0,0,0,...,1,0,0,0,0,0,0,0,0,0
845,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 14:09:00,1 days 21:09:00,1,849,0,0,0,...,1,0,0,0,0,0,0,0,0,0
846,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 14:10:00,1 days 21:10:00,1,850,0,0,0,...,1,0,0,0,0,0,0,0,0,0
40757,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 15:00:00,1 days 22:00:00,1,900,1,1,1,...,0,1,0,0,0,0,0,0,0,0
80695,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 15:41:00,1 days 22:41:00,1,941,1,1,0,...,0,1,0,0,0,0,0,0,0,0
40758,542097,2016-01-20 17:00:00,2016-01-22 17:00:00,2016-01-22 15:44:00,1 days 22:44:00,1,944,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [144]:
#Total slides

sliding(cleaned)

slide starts at:  2014-06-02 09:00:00
(24, 29)

array([[1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])